export const SOCKET_EVENT = {
  SET_INIT: "SET_INIT",
  ENTER_CHATROOM: "ENTER_CHATROOM",
  EXIT_CHATROOM: "EXIT_CHATROOM",
  UPDATE_NICKNAME: "UPDATE_NICKNAME",
  SEND_MESSAGE: "SEND_MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
  GET_CHATROOM_LIST: "GET_CHATROOM_LIST",
  CREATE_CHATROOM: "CREATE_CHATROOM",
};
